version: "3.3"

networks:
  app-network:
    driver: bridge

services:
  mydb:
    image: postgres:latest
    ports: 
    - 5432:5432
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin